name: CI/CD Pipeline for Next.js App

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: next-js-demo-app

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set Up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: next-js-demo-app/package-lock.json
    
    - name: Install Dependencies
      run: npm ci
    - name: Linting
      run: npm run lint


    - name: Building
      run: npm run build

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Docker Build
      run : |
        docker build -t ghcr.io/${{github.repository}}/next-js-demo-app:${{github.sha}} .
        docker tag ghcr.io/${{github.repository}}/next-js-demo-app:${{github.sha}} ghcr.io/${{github.repository}}/next-js-demo-app:latest

    - name: Push Image
      run: |
        docker push ghcr.io/${{github.repository}}/next-js-demo-app:${{github.sha}}
        docker push ghcr.io/${{github.repository}}/next-js-demo-app:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Multiple commands
      uses: appleboy/ssh-action@v1
      with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.KEY }}
           port: ${{ secrets.PORT }}
           script: |
                pwd
                cd /app
                docker-compose stop nextjs-app
                docker-compose rm -f nextjs-app
                docker rmi ghcr.io/rafaynadeem1203/nextjs-js/next-js-demo-app:latest || true
                docker-compose pull nextjs-app
                docker-compose up -d nextjs-app
